name: CI Pipeline

on:
  push:
    branches: 
      - main 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t rezhinabdulrahman/rezhindock:latest .

      - name: Push to Docker Hub
        run: docker push rezhinabdulrahman/rezhindock:latest
